version: "3"

services:
  project_name_nginx:
    container_name: project_name_nginx
    build:
      context: ./images/nginx/1.18
      dockerfile: Dockerfile
    ports:
      - "nginxUnsecurePort:80"
      - "nginxSecurePort:443"
    volumes:
      - ../public_html:/var/www/html/public_html:cached
      - ./conf/nginx/magento2.conf.sample:/etc/nginx/magento2.conf.sample:cached
      - ./conf/nginx/magento2.conf:/etc/nginx/conf.d/magento2.conf:cached
    links:
      - project_name_mysql
      - project_name_php
      - project_name_redis
    restart: always
    networks:
      - project_name_app

  project_name_php:
    container_name: project_name_php
    build:
      context: ./images/php/7.4
      dockerfile: Dockerfile
    ports:
      - "phpFpmPort:9000"
    env_file: env/phpfpm.env
    environment:
      PHP_IDE_CONFIG: serverName=Docker
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - sock:/sock
      - ../public_html/:/var/www/html/public_html:cached
      - ./conf/php/xdebug.ini:/etc/php/7.4/mods-available/xdebug.ini:cached
      - ./conf/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:cached
      - ./conf/php/php.ini:/usr/local/etc/php:cached
      - ./conf/php/msmtprc:/etc/msmtprc:cached
      - ~/.composer:/home/www/.composer:cached
    links:
      - project_name_mysql
      - project_name_elasticsearch
      - project_name_redis
    restart: always
    networks:
      - project_name_app

  project_name_mysql:
    container_name: project_name_mysql
    image: mariadb:10.4
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "mysqlPort:3306"
    env_file: env/db.env
    volumes:
      - - ../public_html/:/var/www/html/public_html:cached
      - ./volumes/mysql:/var/lib/mysql:cached
      - ./images/mysql:/docker-entrypoint-initdb.d:cached
      - ./conf/mysql/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf:cached
    restart: always
    networks:
      - project_name_app

  project_name_elasticsearch:
    container_name: project_name_elasticsearch
    image: elasticsearch:7.9.3
    ports:
      - "elasticsearchPort:9200"
    environment:
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - "cluster.routing.allocation.disk.threshold_enabled=false"
      - "index.blocks.read_only_allow_delete"
    volumes:
      - es-data:/usr/share/elasticsearch/data:cached
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    restart: always
    networks:
      - project_name_app

  project_name_redis:
    container_name: project_name_redis
    image: redis:6.0.16
    restart: always
    networks:
      - project_name_app

  project_name_phpmyadmin:
    container_name: project_name_phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - "phpmyadminPort:80"
    environment:
      - PMA_ARBITRARY=1
    volumes:
      - /sessions
    external_links:
      - mysql
    depends_on:
      - mysql
      - redis
    restart: always
    networks:
      - project_name_app

  project_name_mailcatcher:
    container_name: project_name_mailcatcher
    image: sj26/mailcatcher
    ports:
      - "mailcatcherPort:1080"
    restart: always
    networks:
      - project_name_app

  project_name_rabbitmq:
    container_name: project_name_rabbitmq
    image: rabbitmq:3.8.22-management-alpine
    ports:
      - "rabbitMQPort:5672"
      - "rabbitMQAdminPort:15672"
    env_file: ./env/rabbitmq.env
    volumes:
      - ./volumes/rebbitmq:/var/lib/rabbitmq
    restart: always
    networks:
      - project_name_app

networks:
  project_name_app:
    driver: bridge

volumes:
  sock:
  es-data:
    driver: local